"""add review model

Revision ID: 7da879140e25
Revises: 43fd4bb0f9ef
Create Date: 2026-09-07 12:10:34.905638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da879140e25'
down_revision: Union[str, Sequence[str], None] = '43fd4bb0f9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewee_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.Enum('CLIENT_TO_FREELANCER', 'FREELANCER_TO_CLIENT', name='reviewtype'), nullable=False),
    sa.Column('rating_overall', sa.Integer(), nullable=False),
    sa.Column('rating_communication', sa.Integer(), nullable=True),
    sa.Column('rating_quality', sa.Integer(), nullable=True),
    sa.Column('rating_timeliness', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating_communication IS NULL OR rating_communication BETWEEN 1 AND 5', name='check_reviews_rating_communication_range'),
    sa.CheckConstraint('rating_overall BETWEEN 1 AND 5', name='check_reviews_rating_overall_range'),
    sa.CheckConstraint('rating_quality IS NULL OR rating_quality BETWEEN 1 AND 5', name='check_reviews_rating_quality_range'),
    sa.CheckConstraint('rating_timeliness IS NULL OR rating_timeliness BETWEEN 1 AND 5', name='check_reviews_rating_timeliness_range'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'reviewer_id', name='uq_reviews_contract_reviewer')
    )
    op.create_index('idx_reviews_reviewee_id', 'reviews', ['reviewee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_reviewee_id', table_name='reviews')
    op.drop_table('reviews')
    # remove the PostgreSQL enum after no table depends on it
    sa.Enum(name='reviewtype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
